/**
 * 210+ 常见数学符号测试用例定义
 * 涵盖希腊字母、二元运算符、关系符、箭头、定界符、微积分/大型算子、重音修饰符及其他数学符号
 */

export interface SymbolTestCase {
  id: string;
  name: string;
  latex: string;
  category: string;
}

export const MATH_SYMBOLS_TEST_CASES: SymbolTestCase[] = [
  // 1. 希腊字母小写 (29个)
  { id: 'sym-001', name: 'Alpha', latex: '\\alpha', category: '希腊字母小写' },
  { id: 'sym-002', name: 'Beta', latex: '\\beta', category: '希腊字母小写' },
  { id: 'sym-003', name: 'Gamma', latex: '\\gamma', category: '希腊字母小写' },
  { id: 'sym-004', name: 'Delta', latex: '\\delta', category: '希腊字母小写' },
  { id: 'sym-005', name: 'Epsilon', latex: '\\epsilon', category: '希腊字母小写' },
  { id: 'sym-006', name: 'Varepsilon', latex: '\\varepsilon', category: '希腊字母小写' },
  { id: 'sym-007', name: 'Zeta', latex: '\\zeta', category: '希腊字母小写' },
  { id: 'sym-008', name: 'Eta', latex: '\\eta', category: '希腊字母小写' },
  { id: 'sym-009', name: 'Theta', latex: '\\theta', category: '希腊字母小写' },
  { id: 'sym-010', name: 'Vartheta', latex: '\\vartheta', category: '希腊字母小写' },
  { id: 'sym-011', name: 'Iota', latex: '\\iota', category: '希腊字母小写' },
  { id: 'sym-012', name: 'Kappa', latex: '\\kappa', category: '希腊字母小写' },
  { id: 'sym-013', name: 'Lambda', latex: '\\lambda', category: '希腊字母小写' },
  { id: 'sym-014', name: 'Mu', latex: '\\mu', category: '希腊字母小写' },
  { id: 'sym-015', name: 'Nu', latex: '\\nu', category: '希腊字母小写' },
  { id: 'sym-016', name: 'Xi', latex: '\\xi', category: '希腊字母小写' },
  { id: 'sym-017', name: 'Pi', latex: '\\pi', category: '希腊字母小写' },
  { id: 'sym-018', name: 'Varpi', latex: '\\varpi', category: '希腊字母小写' },
  { id: 'sym-019', name: 'Rho', latex: '\\rho', category: '希腊字母小写' },
  { id: 'sym-020', name: 'Varrho', latex: '\\varrho', category: '希腊字母小写' },
  { id: 'sym-021', name: 'Sigma', latex: '\\sigma', category: '希腊字母小写' },
  { id: 'sym-022', name: 'Varsigma', latex: '\\varsigma', category: '希腊字母小写' },
  { id: 'sym-023', name: 'Tau', latex: '\\tau', category: '希腊字母小写' },
  { id: 'sym-024', name: 'Upsilon', latex: '\\upsilon', category: '希腊字母小写' },
  { id: 'sym-025', name: 'Phi', latex: '\\phi', category: '希腊字母小写' },
  { id: 'sym-026', name: 'Varphi', latex: '\\varphi', category: '希腊字母小写' },
  { id: 'sym-027', name: 'Chi', latex: '\\chi', category: '希腊字母小写' },
  { id: 'sym-028', name: 'Psi', latex: '\\psi', category: '希腊字母小写' },
  { id: 'sym-029', name: 'Omega', latex: '\\omega', category: '希腊字母小写' },

  // 2. 希腊字母大写 (11个)
  { id: 'sym-030', name: 'Gamma 大写', latex: '\\Gamma', category: '希腊字母大写' },
  { id: 'sym-031', name: 'Delta 大写', latex: '\\Delta', category: '希腊字母大写' },
  { id: 'sym-032', name: 'Theta 大写', latex: '\\Theta', category: '希腊字母大写' },
  { id: 'sym-033', name: 'Lambda 大写', latex: '\\Lambda', category: '希腊字母大写' },
  { id: 'sym-034', name: 'Xi 大写', latex: '\\Xi', category: '希腊字母大写' },
  { id: 'sym-035', name: 'Pi 大写', latex: '\\Pi', category: '希腊字母大写' },
  { id: 'sym-036', name: 'Sigma 大写', latex: '\\Sigma', category: '希腊字母大写' },
  { id: 'sym-037', name: 'Upsilon 大写', latex: '\\Upsilon', category: '希腊字母大写' },
  { id: 'sym-038', name: 'Phi 大写', latex: '\\Phi', category: '希腊字母大写' },
  { id: 'sym-039', name: 'Psi 大写', latex: '\\Psi', category: '希腊字母大写' },
  { id: 'sym-040', name: 'Omega 大写', latex: '\\Omega', category: '希腊字母大写' },

  // 3. 二元运算符 (30个)
  { id: 'sym-041', name: 'Plus', latex: 'a + b', category: '二元运算' },
  { id: 'sym-042', name: 'Minus', latex: 'a - b', category: '二元运算' },
  { id: 'sym-043', name: 'PlusMinus', latex: '\\pm', category: '二元运算' },
  { id: 'sym-044', name: 'MinusPlus', latex: '\\mp', category: '二元运算' },
  { id: 'sym-045', name: 'Times', latex: '\\times', category: '二元运算' },
  { id: 'sym-046', name: 'Div', latex: '\\div', category: '二元运算' },
  { id: 'sym-047', name: 'Cdot', latex: '\\cdot', category: '二元运算' },
  { id: 'sym-048', name: 'Ast', latex: '\\ast', category: '二元运算' },
  { id: 'sym-049', name: 'Star', latex: '\\star', category: '二元运算' },
  { id: 'sym-050', name: 'Circ', latex: '\\circ', category: '二元运算' },
  { id: 'sym-051', name: 'Bullet', latex: '\\bullet', category: '二元运算' },
  { id: 'sym-052', name: 'Cap', latex: '\\cap', category: '二元运算' },
  { id: 'sym-053', name: 'Cup', latex: '\\cup', category: '二元运算' },
  { id: 'sym-054', name: 'Uplus', latex: '\\uplus', category: '二元运算' },
  { id: 'sym-055', name: 'Sqcap', latex: '\\sqcap', category: '二元运算' },
  { id: 'sym-056', name: 'Sqcup', latex: '\\sqcup', category: '二元运算' },
  { id: 'sym-057', name: 'Vee', latex: '\\vee', category: '二元运算' },
  { id: 'sym-058', name: 'Wedge', latex: '\\wedge', category: '二元运算' },
  { id: 'sym-059', name: 'Setminus', latex: '\\setminus', category: '二元运算' },
  { id: 'sym-060', name: 'Diamond', latex: '\\diamond', category: '二元运算' },
  { id: 'sym-061', name: 'Bigtriangleup', latex: '\\bigtriangleup', category: '二元运算' },
  { id: 'sym-062', name: 'Bigtriangledown', latex: '\\bigtriangledown', category: '二元运算' },
  { id: 'sym-063', name: 'Oplus', latex: '\\oplus', category: '二元运算' },
  { id: 'sym-064', name: 'Ominus', latex: '\\ominus', category: '二元运算' },
  { id: 'sym-065', name: 'Otimes', latex: '\\otimes', category: '二元运算' },
  { id: 'sym-066', name: 'Oslash', latex: '\\oslash', category: '二元运算' },
  { id: 'sym-067', name: 'Odot', latex: '\\odot', category: '二元运算' },
  { id: 'sym-068', name: 'Wr', latex: '\\wr', category: '二元运算' },
  { id: 'sym-069', name: 'Amalg', latex: '\\amalg', category: '二元运算' },
  { id: 'sym-070', name: 'Dagger', latex: '\\dagger', category: '二元运算' },

  // 4. 关系符与比较符 (35个)
  { id: 'sym-071', name: 'Equal', latex: '=', category: '关系运算' },
  { id: 'sym-072', name: 'NotEqual', latex: '\\neq', category: '关系运算' },
  { id: 'sym-073', name: 'Less', latex: '<', category: '关系运算' },
  { id: 'sym-074', name: 'Greater', latex: '>', category: '关系运算' },
  { id: 'sym-075', name: 'LessEqual', latex: '\\le', category: '关系运算' },
  { id: 'sym-076', name: 'GreaterEqual', latex: '\\ge', category: '关系运算' },
  { id: 'sym-077', name: 'MuchLess', latex: '\\ll', category: '关系运算' },
  { id: 'sym-078', name: 'MuchGreater', latex: '\\gg', category: '关系运算' },
  { id: 'sym-079', name: 'Equiv', latex: '\\equiv', category: '关系运算' },
  { id: 'sym-080', name: 'Sim', latex: '\\sim', category: '关系运算' },
  { id: 'sym-081', name: 'Simeq', latex: '\\simeq', category: '关系运算' },
  { id: 'sym-082', name: 'Approx', latex: '\\approx', category: '关系运算' },
  { id: 'sym-083', name: 'Cong', latex: '\\cong', category: '关系运算' },
  { id: 'sym-084', name: 'Asymp', latex: '\\asymp', category: '关系运算' },
  { id: 'sym-085', name: 'Doteq', latex: '\\doteq', category: '关系运算' },
  { id: 'sym-086', name: 'Propto', latex: '\\propto', category: '关系运算' },
  { id: 'sym-087', name: 'Subset', latex: '\\subset', category: '关系运算' },
  { id: 'sym-088', name: 'Supset', latex: '\\supset', category: '关系运算' },
  { id: 'sym-089', name: 'Subseteq', latex: '\\subseteq', category: '关系运算' },
  { id: 'sym-090', name: 'Supseteq', latex: '\\supseteq', category: '关系运算' },
  { id: 'sym-091', name: 'In', latex: '\\in', category: '关系运算' },
  { id: 'sym-092', name: 'Ni', latex: '\\ni', category: '关系运算' },
  { id: 'sym-093', name: 'Notin', latex: '\\notin', category: '关系运算' },
  { id: 'sym-094', name: 'Parallel', latex: '\\parallel', category: '关系运算' },
  { id: 'sym-095', name: 'Perp', latex: '\\perp', category: '关系运算' },
  { id: 'sym-096', name: 'Prec', latex: '\\prec', category: '关系运算' },
  { id: 'sym-097', name: 'Succ', latex: '\\succ', category: '关系运算' },
  { id: 'sym-098', name: 'Preceq', latex: '\\preceq', category: '关系运算' },
  { id: 'sym-099', name: 'Succeq', latex: '\\succeq', category: '关系运算' },
  { id: 'sym-100', name: 'Sqsubset', latex: '\\sqsubset', category: '关系运算' },
  { id: 'sym-101', name: 'Sqsupset', latex: '\\sqsupset', category: '关系运算' },
  { id: 'sym-102', name: 'Sqsubseteq', latex: '\\sqsubseteq', category: '关系运算' },
  { id: 'sym-103', name: 'Sqsupseteq', latex: '\\sqsupseteq', category: '关系运算' },
  { id: 'sym-104', name: 'Smile', latex: '\\smile', category: '关系运算' },
  { id: 'sym-105', name: 'Frown', latex: '\\frown', category: '关系运算' },

  // 5. 箭头符号 (25个)
  { id: 'sym-106', name: 'Leftarrow', latex: '\\leftarrow', category: '箭头符号' },
  { id: 'sym-107', name: 'Rightarrow', latex: '\\rightarrow', category: '箭头符号' },
  { id: 'sym-108', name: 'leftrightarrow', latex: '\\leftrightarrow', category: '箭头符号' },
  { id: 'sym-109', name: 'Leftarrow 大写', latex: '\\Leftarrow', category: '箭头符号' },
  { id: 'sym-110', name: 'Rightarrow 大写', latex: '\\Rightarrow', category: '箭头符号' },
  { id: 'sym-111', name: 'Leftrightarrow 大写', latex: '\\Leftrightarrow', category: '箭头符号' },
  { id: 'sym-112', name: 'Mapsto', latex: '\\mapsto', category: '箭头符号' },
  { id: 'sym-113', name: 'Hookleftarrow', latex: '\\hookleftarrow', category: '箭头符号' },
  { id: 'sym-114', name: 'Hookrightarrow', latex: '\\hookrightarrow', category: '箭头符号' },
  { id: 'sym-115', name: 'Nearrow', latex: '\\nearrow', category: '箭头符号' },
  { id: 'sym-116', name: 'Searrow', latex: '\\searrow', category: '箭头符号' },
  { id: 'sym-117', name: 'Swarrow', latex: '\\swarrow', category: '箭头符号' },
  { id: 'sym-118', name: 'Nwarrow', latex: '\\nwarrow', category: '箭头符号' },
  { id: 'sym-119', name: 'Uparrow', latex: '\\uparrow', category: '箭头符号' },
  { id: 'sym-120', name: 'Downarrow', latex: '\\downarrow', category: '箭头符号' },
  { id: 'sym-121', name: 'Updownarrow', latex: '\\updownarrow', category: '箭头符号' },
  { id: 'sym-122', name: 'Uparrow 大写', latex: '\\Uparrow', category: '箭头符号' },
  { id: 'sym-123', name: 'Downarrow 大写', latex: '\\Downarrow', category: '箭头符号' },
  { id: 'sym-124', name: 'Updownarrow 大写', latex: '\\Updownarrow', category: '箭头符号' },
  { id: 'sym-125', name: 'Longleftarrow', latex: '\\longleftarrow', category: '箭头符号' },
  { id: 'sym-126', name: 'longrightarrow', latex: '\\longrightarrow', category: '箭头符号' },
  { id: 'sym-127', name: 'longleftrightarrow', latex: '\\longleftrightarrow', category: '箭头符号' },
  { id: 'sym-128', name: 'Longleftarrow 大写', latex: '\\Longleftarrow', category: '箭头符号' },
  { id: 'sym-129', name: 'Longrightarrow 大写', latex: '\\Longrightarrow', category: '箭头符号' },
  { id: 'sym-130', name: 'Longleftrightarrow 大写', latex: '\\Longleftrightarrow', category: '箭头符号' },

  // 6. 微积分与大型算子 (25个)
  { id: 'sym-131', name: 'Integral', latex: '\\int', category: '微积分与算子' },
  { id: 'sym-132', name: 'Double Integral', latex: '\\iint', category: '微积分与算子' },
  { id: 'sym-133', name: 'Triple Integral', latex: '\\iiint', category: '微积分与算子' },
  { id: 'sym-134', name: 'Contour Integral', latex: '\\oint', category: '微积分与算子' },
  { id: 'sym-135', name: 'Summation', latex: '\\sum', category: '微积分与算子' },
  { id: 'sym-136', name: 'Product', latex: '\\prod', category: '微积分与算子' },
  { id: 'sym-137', name: 'Coproduct', latex: '\\coprod', category: '微积分与算子' },
  { id: 'sym-138', name: 'Partial', latex: '\\partial', category: '微积分与算子' },
  { id: 'sym-139', name: 'Nabla', latex: '\\nabla', category: '微积分与算子' },
  { id: 'sym-140', name: 'Infinity', latex: '\\infty', category: '微积分与算子' },
  { id: 'sym-141', name: 'Limit', latex: '\\lim', category: '微积分与算子' },
  { id: 'sym-142', name: 'Supremum', latex: '\\sup', category: '微积分与算子' },
  { id: 'sym-143', name: 'Infimum', latex: '\\inf', category: '微积分与算子' },
  { id: 'sym-144', name: 'Max', latex: '\\max', category: '微积分与算子' },
  { id: 'sym-145', name: 'Min', latex: '\\min', category: '微积分与算子' },
  { id: 'sym-146', name: 'Sin', latex: '\\sin', category: '微积分与算子' },
  { id: 'sym-147', name: 'Cos', latex: '\\cos', category: '微积分与算子' },
  { id: 'sym-148', name: 'Tan', latex: '\\tan', category: '微积分与算子' },
  { id: 'sym-149', name: 'Ln', latex: '\\ln', category: '微积分与算子' },
  { id: 'sym-150', name: 'Log', latex: '\\log', category: '微积分与算子' },
  { id: 'sym-151', name: 'Exp', latex: '\\exp', category: '微积分与算子' },
  { id: 'sym-152', name: 'Sec', latex: '\\sec', category: '微积分与算子' },
  { id: 'sym-153', name: 'Csc', latex: '\\csc', category: '微积分与算子' },
  { id: 'sym-154', name: 'Cot', latex: '\\cot', category: '微积分与算子' },
  { id: 'sym-155', name: 'Arcsin', latex: '\\arcsin', category: '微积分与算子' },

  // 7. 定界符与括号 (15个)
  { id: 'sym-156', name: 'Parentheses', latex: '(x)', category: '定界符' },
  { id: 'sym-157', name: 'Brackets', latex: '[x]', category: '定界符' },
  { id: 'sym-158', name: 'Braces', latex: '\\{ x \\}', category: '定界符' },
  { id: 'sym-159', name: 'Vert', latex: '|x|', category: '定界符' },
  { id: 'sym-160', name: 'Double Vert', latex: '\\|x\\|', category: '定界符' },
  { id: 'sym-161', name: 'Angle', latex: '\\langle x \\rangle', category: '定界符' },
  { id: 'sym-162', name: 'Floor', latex: '\\lfloor x \\rfloor', category: '定界符' },
  { id: 'sym-163', name: 'Ceil', latex: '\\lceil x \\rceil', category: '定界符' },
  { id: 'sym-164', name: 'Backslash', latex: '\\backslash', category: '定界符' },
  { id: 'sym-165', name: 'Uparrow delim', latex: '\\uparrow', category: '定界符' },
  { id: 'sym-166', name: 'Downarrow delim', latex: '\\downarrow', category: '定界符' },
  { id: 'sym-167', name: 'Updownarrow delim', latex: '\\updownarrow', category: '定界符' },
  { id: 'sym-168', name: 'Left/Right parens', latex: '\\left( \\frac{a}{b} \\right)', category: '定界符' },
  { id: 'sym-169', name: 'Left/Right brackets', latex: '\\left[ \\frac{a}{b} \\right]', category: '定界符' },
  { id: 'sym-170', name: 'Left/Right braces', latex: '\\left\\{ \\frac{a}{b} \\right\\}', category: '定界符' },

  // 8. 重音修饰与标记符 (18个)
  { id: 'sym-171', name: 'Vec', latex: '\\vec{x}', category: '重音修饰' },
  { id: 'sym-172', name: 'Hat', latex: '\\hat{x}', category: '重音修饰' },
  { id: 'sym-173', name: 'Bar', latex: '\\bar{x}', category: '重音修饰' },
  { id: 'sym-174', name: 'Tilde', latex: '\\tilde{x}', category: '重音修饰' },
  { id: 'sym-175', name: 'Dot', latex: '\\dot{x}', category: '重音修饰' },
  { id: 'sym-176', name: 'Ddot', latex: '\\ddot{x}', category: '重音修饰' },
  { id: 'sym-177', name: 'Check', latex: '\\check{x}', category: '重音修饰' },
  { id: 'sym-178', name: 'Breve', latex: '\\breve{x}', category: '重音修饰' },
  { id: 'sym-179', name: 'Acute', latex: '\\acute{x}', category: '重音修饰' },
  { id: 'sym-180', name: 'Grave', latex: '\\grave{x}', category: '重音修饰' },
  { id: 'sym-181', name: 'Mathring', latex: '\\mathring{x}', category: '重音修饰' },
  { id: 'sym-182', name: 'Overline', latex: '\\overline{AB}', category: '重音修饰' },
  { id: 'sym-183', name: 'Underline', latex: '\\underline{AB}', category: '重音修饰' },
  { id: 'sym-184', name: 'Overbrace', latex: '\\overbrace{a+b}', category: '重音修饰' },
  { id: 'sym-185', name: 'Underbrace', latex: '\\underbrace{a+b}', category: '重音修饰' },
  { id: 'sym-186', name: 'Widehat', latex: '\\widehat{xyz}', category: '重音修饰' },
  { id: 'sym-187', name: 'Widetilde', latex: '\\widetilde{xyz}', category: '重音修饰' },
  { id: 'sym-188', name: 'Prime', latex: "f'(x)", category: '重音修饰' },

  // 9. 杂项数学符号 (27个)
  { id: 'sym-189', name: 'Forall', latex: '\\forall', category: '杂项符号' },
  { id: 'sym-190', name: 'Exists', latex: '\\exists', category: '杂项符号' },
  { id: 'sym-191', name: 'Nexists', latex: '\\nexists', category: '杂项符号' },
  { id: 'sym-192', name: 'EmptySet', latex: '\\emptyset', category: '杂项符号' },
  { id: 'sym-193', name: 'Varemptyset', latex: '\\varnothing', category: '杂项符号' },
  { id: 'sym-194', name: 'Hbar', latex: '\\hbar', category: '杂项符号' },
  { id: 'sym-195', name: 'Ell', latex: '\\ell', category: '杂项符号' },
  { id: 'sym-196', name: 'Weierstrass p', latex: '\\wp', category: '杂项符号' },
  { id: 'sym-197', name: 'Real', latex: '\\Re', category: '杂项符号' },
  { id: 'sym-198', name: 'Imaginary', latex: '\\Im', category: '杂项符号' },
  { id: 'sym-199', name: 'Aleph', latex: '\\aleph', category: '杂项符号' },
  { id: 'sym-200', name: 'Top', latex: '\\top', category: '杂项符号' },
  { id: 'sym-201', name: 'Bot', latex: '\\bot', category: '杂项符号' },
  { id: 'sym-202', name: 'Angle', latex: '\\angle', category: '杂项符号' },
  { id: 'sym-203', name: 'Triangle', latex: '\\triangle', category: '杂项符号' },
  { id: 'sym-204', name: 'Square', latex: '\\square', category: '杂项符号' },
  { id: 'sym-205', name: 'Blacksquare', latex: '\\blacksquare', category: '杂项符号' },
  { id: 'sym-206', name: 'Diamondsuit', latex: '\\diamondsuit', category: '杂项符号' },
  { id: 'sym-207', name: 'Heartsuit', latex: '\\heartsuit', category: '杂项符号' },
  { id: 'sym-208', name: 'Spadesuit', latex: '\\spadesuit', category: '杂项符号' },
  { id: 'sym-209', name: 'Clubsuit', latex: '\\clubsuit', category: '杂项符号' },
  { id: 'sym-210', name: 'Flat', latex: '\\flat', category: '杂项符号' },
  { id: 'sym-211', name: 'Natural', latex: '\\natural', category: '杂项符号' },
  { id: 'sym-212', name: 'Sharp', latex: '\\sharp', category: '杂项符号' },
  { id: 'sym-213', name: 'Cdots', latex: '\\cdots', category: '杂项符号' },
  { id: 'sym-214', name: 'Vdots', latex: '\\vdots', category: '杂项符号' },
  { id: 'sym-215', name: 'Ddots', latex: '\\ddots', category: '杂项符号' }
];
